name: Autobuild

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Build Quasar
        run: |
          cd ausbildungsnachweise-quasar
          pwd
          npm ci
          npx quasar build

      - name: Move Quasar Build
        run: |
          mkdir -p ../ausbildungsnachweise-quarkus/src/main/resources/META-INF/resources
          pwd
          cp -r dist/spa/* ../ausbildungsnachweise-quarkus/src/main/resources/META-INF/resources
          cd ../ausbildungsnachweise-quarkus

      - name: Build Quarkus
        run: ./mvnw package -Dquarkus.package.type=uber-jar
