name: Autobuild and Release to DockerHub

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:

    runs-on: ubuntu-latest
    # Setup Environment
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Setup Node.js environment
      uses: actions/setup-node@v3.3.0
      with:
        node-version: 16.x

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

# Build Steps

    - name: Build Vue App
      run: |
        cd ausbildungsnachweise-quasar
        npm ci
        npx quasar build
        ls dist/spa

    - name: Copy Quasar Build to Quarkus
      run: |
        mkdir -p ausbildungsnachweise-quarkus/src/main/resources/META-INF/resources
        cp -r ausbildungsnachweise-quasar/dist/spa ausbildungsnachweise-quarkus/src/main/resources/META-INF/resources
        ls ausbildungsnachweise-quarkus/src/main/resources/META-INF/resources

    - name: Build Quarkus Container with Maven and Push to DockerHub
      run: |
        cd ausbildungsnachweise-quarkus
        mvn clean package -Dquarkus.container-image.build=true -Dquarkus.container-image.tag=${{ secrets.DOCKER_HUB_USERNAME }}/ausbildungsnachweise:latest -Dquarkus.container-image.username=${{ secrets.DOCKER_HUB_USERNAME }} -Dquarkus.container-image.password=${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} -Dquarkus.container-image.push=true
