name: Autobuild and Release to DockerHub

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:

    runs-on: ubuntu-latest
    # Setup Environment
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Setup Node.js environment
      uses: actions/setup-node@v3.3.0
      with:
        node-version: 16.x

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

# Build Steps

    - name: Build Vue App
      run: |
        cd ausbildungsnachweise-quasar
        npm ci
        npx quasar build

    - name: Copy Quasar Build to Quarkus
      run: |
        mkdir -p ausbildungsnachweise-quarkus/src/main/resources/META-INF/resources
        cp -r ausbildungsnachweise-quasar/dist/spa ausbildungsnachweise-quarkus/src/main/resources/META-INF/resources

    - name: Build Quarkus with Maven
      run: |
        cd ausbildungsnachweise-quarkus
        mvn clean package

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build Container and Push to DockerHub
      id: docker_build
      uses: docker/build-push-action@v3
      with:
          context: ausbildungsnachweise-quarkus/
          file: ausbildungsnachweise-quarkus/src/main/docker/Dockerfile.jvm
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/ausbildungsnachweise:latest

# Result Logging

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}